library(readxl)
library(xlsx)
pe_smb_by_company <- read_excel("SMB_PERU.xlsx", sheet = "autonomous_system.name")
pe_smb_by_city <- read_excel("SMB_PERU.xlsx", sheet = "location.city")
pe_smb_by_os.vendor <- read_excel("SMB_PERU.xlsx", sheet = "operating_system.vendor")
pe_smbv1_by_company <- read_excel("SMBv1_PERU.xlsx", sheet = "autonomous_system.name")
pe_smbv1_by_city <- read_excel("SMBv1_PERU.xlsx", sheet = "location.city")
pe_smbv1_by_os.vendor <- read_excel("SMBv1_PERU.xlsx", sheet = "operating_system.vendor")
latam_smb_by_company <- read_excel("SMB_LATAM.xlsx", sheet = "autonomous_system.name")
latam_smb_by_country <- read_excel("SMB_LATAM.xlsx", sheet = "location.country")
latam_smb_by_os.vendor <- read_excel("SMB_LATAM.xlsx", sheet = "operating_system.vendor")
latam_smbv1_by_company <- read_excel("SMBv1_LATAM.xlsx", sheet = "autonomous_system.name")
latam_smbv1_by_country <- read_excel("SMBv1_LATAM.xlsx", sheet = "location.country")
latam_smbv1_by_os.vendor <- read_excel("SMBv1_LATAM.xlsx", sheet = "operating_system.vendor")
head("latam_smb_by_os")
