library(readxl)
library(xlsx)
smb_by_company <- read_excel("SMB_PERU.xlsx", sheet = "autonomous_system.name")
smb_by_city <- read_excel("SMB_PERU.xlsx", sheet = "location.city")
smb_by_os.vendor <- read_excel("SMBv1_PERU.xlsx", sheet = "operating_system.vendor")
smbv1_by_company <- read_excel("SMBv1_PERU.xlsx", sheet = "autonomous_system.name")
smbv1_by_city <- read_excel("SMBv1_PERU.xlsx", sheet = "location.city")
smbv1_by_os.vendor <- read_excel("SMBv1_PERU.xlsx", sheet = "operating_system.vendor")